### ISSUE TITLE
The red minuses are confusing on the sensitivities editing screen

### ISSUE THREAD

**Issue by garrettlew** [mmachiya/feather#107]
For the sensitivities screen, when you go to reorder them, there are a bunch of red minus circles on the left hand side. They don't do anything but I expect them to be buttons that remove things. To be sure, you're not suppose to be able to remove anything so it would be more clear if those weren't there.

**Comment by siriwans** [comment]
it is build into when rearranging the table view cells and i cannot find a way to take it out if we dont need to deletion feature
