### ISSUE TITLE
Research tools for webscraping 

### ISSUE THREAD

**Issue by mmachiya** [mmachiya/feather#24]
#7 #12 #23 #14 #18 #17 

Research tools needed to webscrape beauty sites.
Research exactly how to webscrape information from beauty websites.
The info we need:
-photos
-product name/brand
-ingredients
-price
-category
-description
-source

**Comment by siriwans** [comment]
Estimation = 5 hours

**Comment by kaishumiyao** [comment]
4 hours spent
