### ISSUE TITLE
research camera with the journal photo gallery

### ISSUE THREAD

**Issue by siriwans** [mmachiya/feather#43]
how to save photo on our app without having to save it to the phone.
how to use the phone camera for our app.

**Comment by siriwans** [comment]
estimation 5 hours

**Comment by khitran** [comment]
useful link: 
https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/avcam_building_a_camera_app

**Comment by mmachiya** [comment]
5 hours spent
